version: "3.3"

services:
  database:
    container_name: readcsv
    image: postgres:9.6.0
    restart: always
    volumes:
      - ../pgdata_readcsv:/var/lib/postgresql/data
    environment:
      - COMPOSE_PROJECT_NAME=readcsv
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=readcsv
      - POSTGRES_USER=readcsv
    ports:
      - 5432:5432
