# Generated by Django 2.2.5 on 2019-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_csv', models.IntegerField(verbose_name='ID')),
                ('track_name', models.CharField(max_length=255, verbose_name='Track Name')),
                ('n_citacoes', models.IntegerField(blank=True, null=True, verbose_name='Nro. Citações')),
                ('size_bytes', models.IntegerField(blank=True, null=True, verbose_name='Size bytes')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('prime_genre', models.CharField(max_length=255, verbose_name='Prime Genre')),
                ('rating_count_tot', models.IntegerField(verbose_name='Rating Count Tot')),
            ],
        ),
    ]
